/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicAppointmentsRouteImport } from './routes/api/public/appointments'
import { Route as ApiPublicAppointmentsIdRouteImport } from './routes/api/public/appointments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppointmentsRoute = ApiPublicAppointmentsRouteImport.update({
  id: '/api/public/appointments',
  path: '/api/public/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppointmentsIdRoute = ApiPublicAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicAppointmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRouteWithChildren
  '/api/public/appointments/$id': typeof ApiPublicAppointmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRouteWithChildren
  '/api/public/appointments/$id': typeof ApiPublicAppointmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRouteWithChildren
  '/api/public/appointments/$id': typeof ApiPublicAppointmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/.lovable/oauth/consent'
    | '/api/public/appointments'
    | '/api/public/appointments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/.lovable/oauth/consent'
    | '/api/public/appointments'
    | '/api/public/appointments/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/.lovable/oauth/consent'
    | '/api/public/appointments'
    | '/api/public/appointments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicAppointmentsRoute: typeof ApiPublicAppointmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointments': {
      id: '/api/public/appointments'
      path: '/api/public/appointments'
      fullPath: '/api/public/appointments'
      preLoaderRoute: typeof ApiPublicAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointments/$id': {
      id: '/api/public/appointments/$id'
      path: '/$id'
      fullPath: '/api/public/appointments/$id'
      preLoaderRoute: typeof ApiPublicAppointmentsIdRouteImport
      parentRoute: typeof ApiPublicAppointmentsRoute
    }
  }
}

interface ApiPublicAppointmentsRouteChildren {
  ApiPublicAppointmentsIdRoute: typeof ApiPublicAppointmentsIdRoute
}

const ApiPublicAppointmentsRouteChildren: ApiPublicAppointmentsRouteChildren = {
  ApiPublicAppointmentsIdRoute: ApiPublicAppointmentsIdRoute,
}

const ApiPublicAppointmentsRouteWithChildren =
  ApiPublicAppointmentsRoute._addFileChildren(
    ApiPublicAppointmentsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicAppointmentsRoute: ApiPublicAppointmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
